import {
  ArcaneGem,
  ArcaneTome,
  Bow,
  Club,
  Hammer,
  Ink,
  Iron,
  IronWood,
  Item,
  ItemType,
  Manual,
  Paper,
  ScrapStone,
  ScrapWood,
  Sword,
} from "../../Data/Items";
import { FishingSkillId } from "../../Data/Skills/FishingSkill";
import { ForagingSkillId } from "../../Data/Skills/ForagingSkill";
import { HuntingSkillId } from "../../Data/Skills/HuntingSkill";
import sturdyStick from "../../../assets/SturdyStick.png";
import roundRock from "../../../assets/RoundRock.png";

export enum ForestClearingItems {
  SturdyStick = "sturdyStick",
  RoundRock = "roundRock",
  TrustyIronSword = "trustyIronSword",
  TrustyIronwoodBow = "trustyIronwoodBow",
  TrustyArcaneSpellbook = "trustyArcaneSpellbook",
  TrustForestEncyclopedia = "trustForestEncyclopedia",
}

export const ForestClearingItem: Item[] = [
  {
    id: ForestClearingItems.SturdyStick,
    name: "Sturdy Stick",
    description: "A sturdy stick you found on the ground.",
    value: 0,
    type: ItemType.WPN,
    amount: 1,
    unique: false,
    img: sturdyStick,
    weapon: {
      weaponType: Club,
      attackSpeed: 2,
      range: 1,
      material: [{ material: ScrapWood, amount: 10 }], // 20% per repair (50% of base cost, can be reduced, round up)
      rank: 0,
      quality: 1,
      damage: { minDamage: 2, maxDamage: 3 },
      critical: { criticalChance: 0.01, criticalMultiplier: 1.5 },
      durability: { current: 87, max: 100 },
    },
  },
  {
    id: ForestClearingItems.RoundRock,
    name: "Round Rock",
    description: "A round rock.",
    value: 0,
    type: ItemType.WPN,
    amount: 1,
    unique: false,
    img: roundRock,
    weapon: {
      weaponType: Hammer,
      attackSpeed: 4,
      range: 1,
      material: [{ material: ScrapStone, amount: 10 }],
      rank: 0,
      quality: 1,
      damage: { minDamage: 1, maxDamage: 6 },
      critical: { criticalChance: 0.01, criticalMultiplier: 1.5 },
      durability: { current: 98, max: 100 },
    },
  },
  {
    id: ForestClearingItems.TrustyIronSword,
    name: "Trusty Iron Sword",
    description: "A sword you've had by your side for many years.",
    value: 10000,
    type: ItemType.WPN,
    amount: 1,
    unique: true,
    weapon: {
      weaponType: Sword,
      attackSpeed: 2,
      range: 1,
      material: [{ material: Iron, amount: 20 }],
      rank: 3,
      quality: 1,
      damage: { minDamage: 12, maxDamage: 17 },
      critical: { criticalChance: 0.05, criticalMultiplier: 2 },
      durability: { current: 548, max: 1000 },
    },
  },
  {
    id: ForestClearingItems.TrustyIronwoodBow,
    name: "Trusty Ironwood Bow",
    description: "A bow you've had by your side for many years.",
    value: 10000,
    type: ItemType.WPN,
    amount: 1,
    unique: true,
    weapon: {
      weaponType: Bow,
      attackSpeed: 3,
      range: 20,
      material: [{ material: IronWood, amount: 20 }],
      rank: 3,
      quality: 1,
      damage: { minDamage: 15, maxDamage: 21 },
      critical: { criticalChance: 0.05, criticalMultiplier: 2 },
      durability: { current: 425, max: 1000 },
    },
  },
  {
    id: ForestClearingItems.TrustyArcaneSpellbook,
    name: "Trusty Arcane Spellbook",
    description: "An Arcane spellbook you've had by your side for many years.",
    value: 10000,
    type: ItemType.WPN,
    amount: 1,
    unique: true,
    weapon: {
      weaponType: ArcaneTome,
      attackSpeed: 2,
      range: 10,
      material: [
        { material: Paper, amount: 20 },
        { material: Ink, amount: 10 },
        { material: ArcaneGem, amount: 2 },
      ],
      rank: 3,
      quality: 1,
      damage: { minDamage: 13, maxDamage: 17 },
      critical: { criticalChance: 0.1, criticalMultiplier: 2 },
      durability: { current: 673, max: 1000 },
    },
  },
  {
    id: ForestClearingItems.TrustForestEncyclopedia,
    name: "Trusty Forest Encyclopedia",
    description: "An encyclopedia you've had by your side for many years.",
    value: 10000,
    type: ItemType.TOOL,
    amount: 1,
    unique: true,
    tool: {
      toolType: Manual,
      rank: 3,
      quality: 1,
      material: [
        { material: Paper, amount: 20 },
        { material: Ink, amount: 10 },
      ],
      durability: { current: 896, max: 1000 }, // Goes down when doing an activity boosted by manual
      skillDirectBonus: [
        { skill: FishingSkillId.Fishing, value: 2, cap: 30 },
        { skill: HuntingSkillId.Hunting, value: 2, cap: 30 },
        { skill: ForagingSkillId.Foraging, value: 2, cap: 30 },
      ],
      skillMultiplierBonus: [
        { skill: FishingSkillId.Fishing, value: 2, cap: 30 },
        { skill: HuntingSkillId.Hunting, value: 2, cap: 30 },
        { skill: ForagingSkillId.Foraging, value: 2, cap: 30 },
      ],
    },
  },
];
